package:
    name: pyfwfr
    version: 0.1

source:
    path: ../../

build:
    number: 0

requirements:
    build:
        - arrow-cpp >=0.14
        - cmake >=3.2
        - double-conversion
        - gcc_linux-64 >=5.1
        - gxx_linux-64 >=5.1
        - icu=58.2
        - make
        - pkg-config
    host:
        - arrow-cpp >=0.14
        - cython >=0.29
        - double-conversion
        - icu=58.2
        - numpy >=1.14
        - pyarrow >=0.14
        - python=3.7
        - setuptools
    run:
        - {{ pin_compatible('numpy', lower_bound='1.14') }}
        - arrow-cpp >=0.14
        - double-conversion
        - icu=58.2
        - pyarrow >=0.14
        - python=3.7

test:
    commands:
        - python -m unittest pyfwfr.tests.test_fwf -v

about:
    summary: 'Fixed-width file reader'
