# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fwfr-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: conda build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@1.x
        with:
          # If provided, this version of miniconda will be downloaded and installed. Visit https://repo.continuum.io/miniconda/ for more information on available versions.
          miniconda-version: 'latest' # optional, default is 
          auto-activate-base: false 
          conda-build-version: 3.18.11 
          python-version: 3.7
          channels: conda-forge 
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda build conda-recipes/pyfwfr
